### PR TITLE
[ENG-6256] Owncloud tests

### PR DESCRIPTION
**Pull request by Vlad0n20**

### CODE REVIEW

**Review by sh-andriy — CHANGES_REQUESTED** [review]
As the several changes was made to **Owncloud** implementation you have to adjust Unit Tests Slightly:

- The methods `_build_propfind_current_user_principal`, `_build_propfind_displayname`, and `_build_propfind_allprops` have been replaced by module-level constants. So update the test code to reference these constants instead of calling the methods.

- Adjust the methods `test_list_child_items`, `test_get_external_account_id`, `test_get_item_info` to follow newly added changes to implementation

**Comment by sh-andriy** [comment]
Also I noticed that your `PR` has other changes that were added for implementation `PR`, you should update those changes also as Implementation had new recent commits added or perhaps just put in this PR one file for Unit Tests and that's it

**Review by sh-andriy — CHANGES_REQUESTED** [review]
**Overall unit tests look good.**

As **Owncloud** was merged into the **`develop`** branch, update your branch fully with **`develop`** so here in this **PR** It would be only one file (`test_owncloud.py`)

**Review by sh-andriy — APPROVED** [review]
LGTM!

**Review by brianjgeiger — APPROVED** [review]

**Pull request merged**
